language: android
jdk:
- oraclejdk8
sudo: required
dist: trusty
env:
  global:
  - BRANCH_NAME=master
  - ANDROID_BUILD_TOOLS=28.0.3
android:
  components:
  - android-28
  - build-tools-$ANDROID_BUILD_TOOLS
  - extra-google-google_play_services
  licenses:
  - ".+"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- openssl aes-256-cbc -K $encrypted_6ccb8a696b2d_key -iv $encrypted_6ccb8a696b2d_iv -in weatherforecast-d2654-61fb91a5b94b.json.enc -out /tmp/weatherforecast-d2654-61fb91a5b94b.json -d
- yes | sdkmanager "platforms;android-28"
- mkdir "$ANDROID_HOME/licenses" || true
before_script:
- env
- gcloud version || true
- gcloud version
- gcloud config set account sujata.swamy@airfi.aero
- gcloud auth activate-service-account --key-file /tmp/weatherforecast-d2654-61fb91a5b94b.json


#script: "./firebase1.sh"
env.global:
- openssl aes-256-cbc -K $encrypted_702b7083e2d9_key -iv $encrypted_702b7083e2d9_iv
  -in google-services.json.enc -out /tmp/google-services.json -d
- openssl aes-256-cbc -K $encrypted_702b7083e2d9_key -iv $encrypted_702b7083e2d9_iv
  -in google-services.json.enc -out google-services.json -d
