language: android
jdk:
- oraclejdk8
sudo: required
dist: trusty
env:
  global:
  - BRANCH_NAME=master
  - ANDROID_BUILD_TOOLS=28.0.3
android:
  components:
  - android-28
  - build-tools-$ANDROID_BUILD_TOOLS
  - extra-google-google_play_services
  licenses:
  - ".+"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- openssl aes-256-cbc -K $encrypted_702b7083e2d9_key -iv $encrypted_702b7083e2d9_iv
  -in google-services.json.enc -out google-services.json -d
- yes | sdkmanager "platforms;android-28"
- mkdir "$ANDROID_HOME/licenses" || true
before_script:
- env
- gcloud version || true
- gcloud version
- gcloud config set account sujata.swamy@airfi.aero
- gcloud auth activate-service-account travis-ci-demo-2@travis-ci-demo-4efee.iam.gserviceaccount.com
  --key-file=travis-ci-demo-4efee-a0e3092d8cd2.json --project=travis-ci-demo-4efee
script: "./firebase1.sh"
env.global:
- openssl aes-256-cbc -K $encrypted_702b7083e2d9_key -iv $encrypted_702b7083e2d9_iv
  -in google-services.json.enc -out google-services.json -d
