language: android
jdk:
- oraclejdk8
sudo: required
dist: trusty
env:
  global:
  - BRANCH_NAME=master
  - ANDROID_BUILD_TOOLS=29.0.3
android:
  components:
  - android-29
  - build-tools-$ANDROID_BUILD_TOOLS
  - extra-google-google_play_services
  licenses:
  - ".+"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- openssl aes-256-cbc -K $encrypted_6ccb8a696b2d_key -iv $encrypted_6ccb8a696b2d_iv -in weatherforecast-d2654-4cca52839c71.json.enc -out /tmp/weatherforecast-d2654-4cca52839c71.json -d
- yes | sdkmanager "platforms;android-29"
- mkdir "$ANDROID_HOME/licenses" || true
before_script:
#- env
#- gcloud version || true
#- gcloud version
#- gcloud config set account sujata.swamy@airfi.aero
#- gcloud auth activate-service-account --key-file /tmp/weatherforecast-d2654-61fb91a5b94b.json
  - env
#  - gcloud version || true

#  - gcloud version

#  - gcloud config set account sujatagopalswamy@gmail.com
#  - gcloud auth activate-service-account weatherforecastdemo@weatherforecast-d2654.iam.gserviceaccount.com --key-file=/tmp/weatherforecast-d2654-4cca52839c71.json --project=weatherforecast-d2654

#- gcloud firebase test android models list
#- gcloud firebase test android versions list
#
#- ./gradlew build assembleDebug
#- gcloud firebase test android run --app app/build/outputs/apk/debug/app-debug.apk --type=robo --device model=Nexus4,version=19

script:

  "./firebase1.sh"
#env.global:
#- openssl aes-256-cbc -K $encrypted_702b7083e2d9_key -iv $encrypted_702b7083e2d9_iv
#  -in google-services.json.enc -out /tmp/google-services.json -d
#- openssl aes-256-cbc -K $encrypted_702b7083e2d9_key -iv $encrypted_702b7083e2d9_iv
#  -in google-services.json.enc -out google-services.json -d
